spring.application.name=roommatch

spring.datasource.url=jdbc:postgresql://localhost:5432/roommatch
spring.datasource.username=postgres
spring.datasource.password=hemant7778
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
roommatch.app.jwtSecret=roomMatchSecretKeyAuthenticationTokenKeyForRoomMateMatcherApplication
roommatch.app.jwtExpirationMs=86400000

server.error.include-message=always

# Multipart configurations for uploading large videos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
